schema_version: 1

context:
  name: playwright
  version: "1.58.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/microsoft/${{ name }}/archive//v${{ version }}.tar.gz
  sha256: b1a7eac4151aab9c51cb7d1ee7825432d62296f0df5d8301645e5ef320d91d04

build:
  number: 0

requirements:
  build:
    - if: not win
      then: nodejs
      else: m2w64-jq
  host:
    - yarn <2
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - if: not win
        then: playwright --version | grep "${{ version }}"
        else:
          - playwright --version | findstr "${{ version }}"
          - where playwright

about:
  summary: Playwright is a framework for Web Testing and Automation. It allows testing Chromium, Firefox and WebKit with a single API.
  description: |
    Playwright is a framework for Web Testing and Automation. It allows
    testing Chromium, Firefox and WebKit with a single API.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://playwright.dev
  repository: https://github.com/microsoft/playwright
  documentation: https://playwright.dev/docs/

extra:
  recipe-maintainers:
    - jan-janssen
    - IzerOnadimQC
